### ISSUE TITLE
CaaS ENTSOE helm chart image tag is no longer available

### ISSUE THREAD

**Issue by galledohm** [caas-team/caas-carbon-footprint#16]
Suggest to modify the "0.0.12" tag value with "0.0.13". Otherwise the Helm Chart fails to retrieve the image by default.

https://github.com/caas-team/caas-carbon-footprint/blob/84c98be706f608403d4d936031d9d814af47a50e/chart/values.yaml#L27

**Comment by eumel8** [comment]
thanks for the hint, should be fixed in https://github.com/caas-team/caas-carbon-footprint/releases/tag/0.0.14

This release includes also updates in [Kepler](https://github.com/sustainable-computing-io/kepler/compare/v0.7.8...v0.7.11)

**Comment by y-eight** [comment]
Please use tagged release v0.0.14
